# Constants of the values

SECTOR_MIN_SYSTEM = 200
SECTOR_MAX_SYSTEM = 250
SECTOR_MAX_RADIUS = 100
ROCKY_PLANET_MAX_SIZE = 30
ROCKY_PLANET_MIN_SIZE = 2
GAS_PLANET_MIN_SIZE = 25
GAS_PLANET_MAX_SIZE = 70
CIV_STARTING_POPULATION = 100000
CIV_STARTING_POP_STORAGE_MAX = 1000000
RAW_RESOURCE_MIN = 5000
RAW_RESOURCE_CAP = 10000
RAW_RESOURCE_TYPES_COUNT = 5

civ_default_values = {"space_telescope_range":10}
civ_multiplcation_values = {}